platform :ios, '16.0'
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})',
  __dir__
]).strip

prepare_react_native_project!

inhibit_all_warnings! # 불필요한 경고 무시

target 'kinover_frontend' do
  config = use_native_modules!

  # ✅ Firebase만 modular_headers 붙이기
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true

  # ⚠️ react-native-screens는 그냥 path만!
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native', :modular_headers => true
  pod 'kakao-login', :path => '../node_modules/@react-native-seoul/kakao-login', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :fabric_enabled => false,
    :hermes_enabled => true
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end
